# Generated by Django 2.2.6 on 2019-10-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorFName', models.CharField(max_length=50)),
                ('authorLName', models.CharField(max_length=50)),
                ('bookTitle', models.CharField(max_length=150)),
                ('bookCat', models.CharField(max_length=50)),
                ('bookDsc', models.TextField()),
                ('bookImg', models.ImageField(upload_to='pics')),
                ('bookPrice', models.IntegerField()),
                ('bookSale', models.BooleanField(default=False)),
            ],
        ),
    ]
