# Generated by Django 2.2.6 on 2019-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authorFName',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authorLName',
        ),
        migrations.AddField(
            model_name='book',
            name='bookAuthor',
            field=models.CharField(default='a', max_length=128),
        ),
        migrations.AddField(
            model_name='book',
            name='bookFreeShip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='bookISBN',
            field=models.BigIntegerField(default=11111),
        ),
        migrations.AddField(
            model_name='book',
            name='bookLang',
            field=models.CharField(choices=[('ENG', 'English'), ('GER', 'German'), ('ESP', 'Spanish')], default='EN', max_length=3),
        ),
        migrations.AddField(
            model_name='book',
            name='bookPages',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='bookPblshr',
            field=models.CharField(default='a', max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookCat',
            field=models.CharField(default='a', max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookDsc',
            field=models.TextField(default='a', max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookTitle',
            field=models.CharField(default='a', max_length=128),
        ),
    ]
