# Generated by Django 2.2.6 on 2019-10-30 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autFirstN', models.CharField(max_length=64)),
                ('autMidN', models.CharField(max_length=64)),
                ('autLastN', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bookAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author'),
            preserve_default=False,
        ),
    ]
